### PR TITLE
Changed int data types for area to unsigned int. fprintf format

### PR DESCRIPTION
**Pull request by mooredan**
from %d to %u. Eliminates negative values in extract file.

### CODE REVIEW

**Review by RTimothyEdwards — COMMENTED** [review]
I have to check this carefully.  Negative areas are absolutely allowed in magic, as are negative capacitances, as they are adjustments to double-counting through a hierarchy.  That's probably not relevant within ExtBasic, but I want to make sure.

**Comment by mooredan** [comment]
This goes along with Isuue #50  - the issue occurs when the value of the area "rolls over" to negative side (msb gets set).  As lambda gets smaller, the more likely this will occur -- that's how I stumbled upon it.   Not necessarily from a real design, but in testing a tech file where lamba went from 0.3um to 0.05um and making big rectangles.

**Comment by RTimothyEdwards** [comment]
Then I think the solution is to increase the type size of the variable holding area, not to change to unsigned.  But I can make this fix, and thanks for debugging it.

**Comment by RTimothyEdwards** [comment]
I just checked in (to opencircuitdesign.com master branch of magic) a fix for this problem using double long integers.  I'd appreciate it if you could confirm the fix.

**Comment by mooredan** [comment]
pulled from opencircuitdesign.com / master, then make and make install

$ git pull beta master
remote: Counting objects: 27, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 18 (delta 14), reused 0 (delta 0)
Unpacking objects: 100% (18/18), 2.02 KiB | 345.00 KiB/s, done.
From git://opencircuitdesign.com/magic
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> beta/master
Updating 5005f77..d6eeb90
Fast-forward
 VERSION               |  2 +-
 extract/ExtBasic.c    | 15 +++++++++------
 extract/extractInt.h  |  2 +-
 tcltk/ext2sim.sh.in   |  4 ++--
 tcltk/ext2spice.sh.in |  4 ++--
 tcltk/magic.sh.in     |  2 +-
 6 files changed, 16 insertions(+), 13 deletions(-)

removed the old .ext file and re-extracted the test case -- still get the negative value:


mooredan@centos:~/projects/ula/mag$ rm mtc2.ext
mooredan@centos:~/projects/ula/mag$ mag2ext -c mtc2
mooredan@centos:~/projects/ula/mag$ cat  mtc2.ext
timestamp 1607100556
version 8.3
tech amic5n
style ngspice
scale 1000 1 1
resistclasses 816000 816000 82400 102700 22300 41300 41300 85 85 40
node "m1_0_0#" 0 -5.71993e+06 0 0 m1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -2146644796 185400 0 0 0 0
substrate "vss" 0 0 -1073741817 -1073741817 space 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

The cell is just a big piece of metal1:
mooredan@centos:~/projects/ula/mag$ cat mtc2.mag
magic
tech amic5n
timestamp 1607100556
<< metal1 >>
rect 0 0 46350 46350
<< end >>

I did think about changing the data type to a "long int", but it wasn't clear if that would have other ill effects.  I can look at the solution again?  ....or I can pass along my tech file.

**Comment by mooredan** [comment]
Closing - replacing with new pull request

**Pull request closed without merging**
