### PR TITLE
3 x crash fix and 1 x read uninitialized fix

### PR DESCRIPTION
**Pull request by dlmiles**
The `findUse()` probably wants a better review to confirm the UNDO operation left in place is enough, in particular DBundo.c:812

### CODE REVIEW

**Review by dlmiles — COMMENTED** [review]
Maybe the real fix this should be `if (ll != NULL)`  ???   camlaWrite.c:1443

**Comment by dlmiles** [comment]
I took my own suggestion after review in comment https://github.com/RTimothyEdwards/magic/pull/314#pullrequestreview-2096688410 

Also looking at the lef/lefWrite.c there was another nearby site which looks like it could trigger the same problem, so I put in the same if() guard.  I can also see the same check exists already around line 1560.

There is one more site around line 1723 that is unclear if there is a risk there also.

**Review by RTimothyEdwards — APPROVED** [review]
All of this looks good to me.
I do wish you would put a space after "if", though . . . "if(x)" is not a function call.

**Comment by RTimothyEdwards** [comment]
Pulled and merged.

**Pull request closed without merging**
