### PR TITLE
Devcap2subckt

### PR DESCRIPTION
**Pull request by mooredan**
When active, the option transforms the device capacitors
from a "C" card to a "X" card (a subckt instance) and adds
an additional connection to the substrate node

e.g.

CN a b capmodel l=2.0u w=2.0u

becomes

XM a b subnode capmodel l=2.0u w=2.0u

The instance numbers "N" and "M" are whatever number is next
for that type of instance.

Two significant changes:

- char *substr   is made global so that it can be availabe in the
EFVisitDevs function.

- call to EFVisitNodes moved to the beginning of the routine
so that the substrate node name is found before calling
EFVisitDevs

This only affects device capacitors which have been extracted.
Future enhancement would be to designate which particular
devices it affects, and whether or not to add the substrate node.

### CODE REVIEW

**Comment by RTimothyEdwards** [comment]
There is already an extraction device type "csubcircuit" which generates an X record for capacitor devices.

**Comment by mooredan** [comment]
Thanks Tim,  Unfortunately I didn't see any documentation for csubcircuit (there's some for rsubcircuit).  I gave it a try and it worked.  What's missing is the third terminal for the substrate.  I don't propose that this be the default behavior, but would you consider a modification for adding an option to add the third terminal.  Without it, I don't see the path to adding back the capacitance between the bottom plate (poly) and the substrate.

**Comment by mooredan** [comment]
Sorry, spoke too soon.  extract/ExtTech.c shows how this can be used.

I would like to do something like this:

device csubcircuit <deviceName> <types1> <types2> None $SUB <cap/area>

I used this but then $SUB shows up in the .ext file instead of what I have set SUB too:

set SUB vss

The other thing is that I'm not seeing the w= and l= parameters. :(

**Comment by mooredan** [comment]
Here's the pertinent difference in the .ext file when using device capacitor vs. device csubcircuit

device devcap poly2Capacitor 101 55 102 56 16 34 "vss" 0 0 "vdd" 100 0

device csubckt poly2Capacitor 101 55 102 56 "None" "vss" 0 0 "vdd" 100 0

Note that the w= and l= values (16 34) is missing in the latter.

Once I figure out how to use this, I'll volunteer to document it for the next guy.

**Comment by RTimothyEdwards** [comment]
But it is documented---see http://opencircuitdesign.com/magic ;  Click on "Technology Files" and then go to the link under "The Magic Technology File Manual".  Find the section for "extract", then scroll down to the paragraph "Device Extraction".  This shows you how to add the substrate node and how to set up parameters like length and width.

**Comment by mooredan** [comment]
My oversight, I was looking here and incorrectly assumed that this was all the documentation that there was, and looked no further.

image

Well after several iterations, I correctly composed this extract section line:

```
device csubcircuit poly2Capacitor (poly2,ecap,phr,p2c)/active (poly,fp,rp,pc,pc)/active space/w l=l w=w
```
...which resulted in this line in the .ext file:

```
device csubckt poly2Capacitor 27 8 28 9 l=20 w=22 "vss" "b1" 0 0 "a1" 84 0
```
...which then resulted in the anticipated line in the spice file:

```
X0 b1 a1 vss poly2Capacitor w=6.6u l=6u
```

Issue #45 that I reported yesterday is still there though.

No need for the pull, the desired functionality is already present. Thanks for your time and assistance.

**Pull request closed without merging**
