### PR TITLE
Adding CI to Magic via Vezzal

### PR DESCRIPTION
**Pull request by lankasaicharan**

### CODE REVIEW

**Review by RTimothyEdwards — CHANGES_REQUESTED** [review]
You misspelled "Continuous" in the README file.

**Comment by lankasaicharan** [comment]
> You misspelled "Continuous" in the README file.

Modified.

**Review by RTimothyEdwards — APPROVED** [review]
Looks good to me.

**Comment by lankasaicharan** [comment]
> Looks good to me.

Thank you for approving.

**Comment by RTimothyEdwards** [comment]
Pulled and merged, and forced a mirror update on github.

**Pull request closed without merging**
