### PR TITLE
MSubcircuit attribute extraction fix

### PR DESCRIPTION
**Pull request by belohoub**
This pull-request is related to issue #32 

swap Drain/Source moved into a function to encapsulate swap-related tasks; area parameters swapped according to the D/S attributes; SPICE attribute comment printf moved to the end of export function as it allows to add more device types

### CODE REVIEW

**Comment by RTimothyEdwards** [comment]
Mostly correct.  The search over parameters should not be searching for the "as", "ad", etc., strings;  it should just be swapping the parameter values for a1 and a2, p1 and p2.  I will pull and fix up the code.  As for the split between ext2spice.c and ext2hier.c:  Yes, there is some redundant code between the two, but I have not spent the time to try to get rid of it.  There are also a number of differences between the hierarchical and flattened output that it has to be done with a bit of care.  Mostly, though, it's just like that because I wrote ext2hier.c without knowing how easy or difficult it was going to be to get magic to write a hierarchical SPICE netlist output.  It turned out to be not as bad as I expected.  But I kept the code separate just in case I ran into a roadblock and had to start over.

**Comment by RTimothyEdwards** [comment]
I realized that your code has the problem that because it is reversing the parameter definitions, they remain swapped until another swap is issued;  meanwhile, if any device is not swapped, then it gets the wrong AD, AS, PD, PS values.  So I just flagged if the swap was done, and always revert the parameters back to the original definition at the end of writing out the device.  Please check that I have not messed up the code and that it still works as you expect.  If so, I will close this pull request (Note:  Changes were updated on the opencircuitdesign.com repo master branch and will not appear in the github repo until the overnight mirror, about 14 hours from now).

**Comment by belohoub** [comment]
@RTimothyEdwards Great, thank you! That make sense - I'll test your fix and let you know.

And thank you for your explenations - that make sense!

So, e.g. spcdevVisit() is completely deprecated function or it is called under some settings? It's still not clear to me (I dumped all the function calls inside magic ...) :-( 

I understand the reasons, why you left the original code for reference (or it is executed sometimes ??); and that rewriting such a complex code may lead to number of regressions, however removing the obviously deprecated code should cause no damage compared to replacing function calls (from the user perspective) - it is always possible to find it in the project history and it removes lot of confusion when studying the code ... if spcdevVisit() is really completely deprecated, then even you were confused :-)

**Comment by RTimothyEdwards** [comment]
Not deprecated:  You can find it referenced in ext2spice.c lines 923 and 1090.  This is called when generating a flattened netlist (option "ext2spice hierarchy off").

**Comment by belohoub** [comment]
Aha, I got it! 
It's hard for me to trace it (from some reason, I believed, that it's controlled by esDistrJunct variable leading to an undocumented switch)
 I'm sorry for the annoying comments!

Thank you!

**Pull request merged**
