### PR TITLE
Add AppImage Building Capabilities

### PR DESCRIPTION
**Pull request by donn**
(Take two)

+ Adds a GitHub Actions flow that builds an AppImage (see AppImages.org) that can produce a monolithic magic binary
~ Fix a portability issue in tcltk/magic.sh.in

This binary should theoretically work on any Linux distro with Glibc 2.17+ and Cairo 1.8+, which is any up to date distro in the last couple years.

### CODE REVIEW

**Comment by donn** [comment]
Argh, forget about it. The Dockerfile isn't building consistently. :(

**Comment by donn** [comment]
Updated to CentOS 7. I'm sure everyone on Ubuntu 12.04 will be devastated by this news.

**Review by RTimothyEdwards — APPROVED** [review]
All of this looks good.  Time for a 2nd attempt.

**Comment by RTimothyEdwards** [comment]
Done, and merged cleanly.

**Pull request closed without merging**
